driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
  - name: ubuntu-12.04
    run_list:
      - recipe[apt::default]
  - name: centos-6.4

suites:
  - name: default
    run_list:
      - recipe[xml::default]
  - name: ruby
    run_list:
      - recipe[xml::ruby]
  - name: no-sys-libs
    run_list:
      - recipe[xml::ruby]
    attributes:
      xml:
        nokogiri:
          use_system_libraries: false
