driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.7
  - name: centos-7.1
  - name: ubuntu-12.04
    run_list:
      - recipe[apt::default]
  - name: ubuntu-14.04
    run_list:
      - recipe[apt::default]

suites:
  - name: default
    run_list:
      - recipe[xml::default]
  - name: ruby
    run_list:
      - recipe[xml::ruby]
  - name: ruby-syslibs
    run_list:
      - recipe[xml::ruby]
    attributes:
      xml:
        nokogiri:
          use_system_libraries: true
          version: "1.6.1"
